#!/usr/bin/env bash
kscreen_output=$(kscreen-doctor -j)

# get DisplayPort 1 ID (left screen). Name: S2719DGF/7BW05V2
left_screen_id=$(jq '.outputs[] | select(.name | contains("DP-2")) | .id' <<< $kscreen_output)

# get DisplayPort 2 ID (right screen). Name: S2719DGF/9VM05V2
right_screen_id=$(jq '.outputs[] | select(.name | contains("DP-1")) | .id' <<< $kscreen_output)

# get HDMI 1 ID (TV). Name: SAMSUNG/16780800
tv_id=$(jq '.outputs[] | select(.name | contains("HDMI-A-2")) | .id' <<< $kscreen_output)

# update screen settings
kscreen-doctor \
    output.$left_screen_id.mode.2560x1440@144 \
    output.$left_screen_id.position.0,0 \
    output.$left_screen_id.enable \
    output.$right_screen_id.mode.2560x1440@144 \
    output.$right_screen_id.position.2560,0 \
    output.$right_screen_id.enable \
    output.$right_screen_id.primary \
    output.$tv_id.disable

# change default pulseaudio (or pipewire-pulse) output to "pc" (see respective script)
pa pc
